### ISSUE TITLE
line margin `-l` does not work with 0

### ISSUE THREAD

**Issue by el10savio** [huytd/comby-search#1]
Hi there, thanks a lot for building comby-search. It's been absolutely helpful wrapping comby and searching together!

Unfortunately, there's an issue with the line margin property. I was expecting it to show no margins when passing 0 to it and only the matched line. Also, when I pass other values, it returns a different margin. An example is shown below 

```
$ ls
test.txt
$ bat test.txt     
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: test.txt
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ a
   2   │ cat
   3   │ in
   4   │ the
   5   │ hat
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
$ cb -f '*.txt' 'cat' -l 0
test.txt
   2 │ cat
   3 │ in
```

I was expecting it to only show
```
$ cb -f '*.txt' 'cat' -l 0
test.txt
   2 │ cat
```

<strike>
Also, these outputs don't match for `1` & `2`
```
$ cb -f '*.txt' 'cat' -l 1
test.txt
   1 │ a
   2 │ cat
   3 │ in
   4 │ the
$ cb -f '*.txt' 'cat' -l 2
test.txt
   1 │ a
   2 │ cat
   3 │ in
   4 │ the
   5 │ hat
```
</strike>

**Comment by huytd** [comment]
Hey, thank you so much for the feedback! I've pushed a new commit to fix this issue.

With `-l 0`:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/613943/225473181-77c7fb86-7818-4589-864e-1edf8009b9ca.png">

With `-l 2`:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/613943/225473591-6ef99288-04b4-4423-a80e-7628aebe2da6.png">

---

Regarding the issue that outputs don't match for 1 & 2, I think it's an expected behavior, since the match is at the top of the file, the case `-l 1` should show the match at line 2, and line 1 and 3 as a margin. The case `-l 2`, it should show the margin lines up to line 4 in the bottom, and on top, the minimum will be line 1, right? Or I missed anything? :D

**Comment by el10savio** [comment]
Hey @huytd, 

Thank you so much for the fix. I will pull the latest version and test it out. 

Yep, I rechecked for the cases of -l `1` & `2`, and it makes sense. I'll strikethrough the issue description since its not a bug.

Closing the issue since it's fixed.

**Comment by el10savio** [comment]
Tested and it works perfectly.

```
$ cb -l 0 -f '*.txt' 'cat'  
test.txt
   2 │ cat
$ cb -l 1 -f '*.txt' 'cat'
test.txt
   1 │ a
   2 │ cat
   3 │ in
```
